### ISSUE TITLE
Vim Gutter to show breakpoints

### ISSUE THREAD

**Issue by zinahe** [sc0ty/gdb-vimview#2]
Hi,
Thank you for sharing gdb-vimview. Is it difficult to add a Vim-side plug-in that adds a gutter to show breakpoints and watches similar to what vim-gitgutter does with code changes ?

Regards,

**Comment by sc0ty** [comment]
I was thinking about it. Vim-side plug-in is probably not necessary since you could call any vim command remotely.
Signs api is documented here http://vimdoc.sourceforge.net/htmldoc/sign.html
It would be a nice feature to have, but I probably will not implement it any time soon.
Pull requests are always welcome.

**Comment by zinahe** [comment]
Thanks. Just submitted a pull request. Cheers,

**Comment by sc0ty** [comment]
Pull request was merged, thanks.
https://github.com/sc0ty/gdb-vimview/pull/3
